"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-01 13:32:01.953237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('admin', 'member', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('meeting_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_series_title'), 'meeting_series', ['title'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('participants_only', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'recording', 'metadata_saved', 'queued', 'processing', 'validating', 'completed', 'failed', name='meetingstatus'), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('additional_memo', sa.Text(), nullable=True),
    sa.Column('local_base_path', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['meeting_series.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_meeting_date'), 'meetings', ['meeting_date'], unique=False)
    op.create_index(op.f('ix_meetings_owner_id'), 'meetings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_table('export_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.Enum('markdown', 'pdf', name='exporttype'), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_files_meeting_id'), 'export_files', ['meeting_id'], unique=False)
    op.create_table('meeting_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.Enum('general_meeting', 'task_assignment', 'project_planning', 'wbs_planning', 'decision_meeting', 'retrospective', 'hr_sensitive', 'architecture_review', 'incident_review', 'unknown', name='meetingtype'), nullable=False),
    sa.Column('one_line_summary', sa.Text(), nullable=False),
    sa.Column('detailed_summary', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('next_agenda', sa.JSON(), nullable=False),
    sa.Column('next_decision_items', sa.JSON(), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_analyses_meeting_id'), 'meeting_analyses', ['meeting_id'], unique=False)
    op.create_table('meeting_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('audio', 'screen_recording', 'memo_json', 'metadata_json', 'image', 'document', 'attachment', name='filetype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('stored_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('local_source_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_files_file_type'), 'meeting_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_meeting_files_meeting_id'), 'meeting_files', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_files_uploaded_by'), 'meeting_files', ['uploaded_by'], unique=False)
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_meeting', sa.Enum('host', 'participant', 'observer', name='roleinmeeting'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_participant')
    )
    op.create_index(op.f('ix_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'validating', 'completed', 'failed', name='processingjobstatus'), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=False)
    op.create_index('ix_processing_jobs_meeting_created', 'processing_jobs', ['meeting_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_meeting_id'), 'processing_jobs', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_table('timeline_memos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('audio_elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('screen_elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_memos_author_id'), 'timeline_memos', ['author_id'], unique=False)
    op.create_index(op.f('ix_timeline_memos_meeting_id'), 'timeline_memos', ['meeting_id'], unique=False)
    op.create_table('meeting_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('transcript_type', sa.Enum('audio', 'screen_audio', 'merged', name='transcripttype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['meeting_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_transcripts_meeting_id'), 'meeting_transcripts', ['meeting_id'], unique=False)
    op.create_table('meeting_visual_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('frame_time_ms', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_type', sa.Enum('ppt_slide', 'architecture_diagram', 'whiteboard', 'document_capture', 'unknown', name='imagetype'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detected_text', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['meeting_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_visual_analyses_meeting_id'), 'meeting_visual_analyses', ['meeting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_visual_analyses_meeting_id'), table_name='meeting_visual_analyses')
    op.drop_table('meeting_visual_analyses')
    op.drop_index(op.f('ix_meeting_transcripts_meeting_id'), table_name='meeting_transcripts')
    op.drop_table('meeting_transcripts')
    op.drop_index(op.f('ix_timeline_memos_meeting_id'), table_name='timeline_memos')
    op.drop_index(op.f('ix_timeline_memos_author_id'), table_name='timeline_memos')
    op.drop_table('timeline_memos')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_meeting_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_meeting_created', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_job_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_meeting_participants_user_id'), table_name='meeting_participants')
    op.drop_table('meeting_participants')
    op.drop_index(op.f('ix_meeting_files_uploaded_by'), table_name='meeting_files')
    op.drop_index(op.f('ix_meeting_files_meeting_id'), table_name='meeting_files')
    op.drop_index(op.f('ix_meeting_files_file_type'), table_name='meeting_files')
    op.drop_table('meeting_files')
    op.drop_index(op.f('ix_meeting_analyses_meeting_id'), table_name='meeting_analyses')
    op.drop_table('meeting_analyses')
    op.drop_index(op.f('ix_export_files_meeting_id'), table_name='export_files')
    op.drop_table('export_files')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_owner_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_meeting_date'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_meeting_series_title'), table_name='meeting_series')
    op.drop_table('meeting_series')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

